"""empty message

Revision ID: 23613fa22584
Revises: ffe357f62eb2
Create Date: 2019-07-17 11:27:27.700394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23613fa22584'
down_revision = 'ffe357f62eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('NAME', sa.String(length=150), nullable=False))
    op.drop_constraint('company_name_key', 'company', type_='unique')
    op.create_unique_constraint(None, 'company', ['NAME'])
    op.drop_column('company', 'name')
    op.add_column('employee', sa.Column('EMAIL', sa.String(length=250), nullable=False))
    op.add_column('employee', sa.Column('NAME', sa.String(length=250), nullable=False))
    op.drop_column('employee', 'name')
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('employee', 'NAME')
    op.drop_column('employee', 'EMAIL')
    op.add_column('company', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company', type_='unique')
    op.create_unique_constraint('company_name_key', 'company', ['name'])
    op.drop_column('company', 'NAME')
    # ### end Alembic commands ###
