"""empty message

Revision ID: 40b5fa05d974
Revises: 54cde1144989
Create Date: 2019-07-16 13:46:42.633614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b5fa05d974'
down_revision = '54cde1144989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'm_company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('m_company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
