"""empty message

Revision ID: 54cde1144989
Revises: 6945474c64c3
Create Date: 2019-07-16 11:18:01.110245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cde1144989'
down_revision = '6945474c64c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('m_company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'm_company_id')
    # ### end Alembic commands ###
