"""empty message

Revision ID: ffe357f62eb2
Revises: 
Create Date: 2019-07-17 11:25:50.415707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe357f62eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('M_COMPANY_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('M_COMPANY_ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee',
    sa.Column('M_EMPLOYEE_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('M_COMPANY_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['M_COMPANY_ID'], ['company.M_COMPANY_ID'], ),
    sa.PrimaryKeyConstraint('M_EMPLOYEE_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('company')
    # ### end Alembic commands ###
